version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: "backend-sequelize-node_postgres"
    environment:
      - POSTGRES_DB=backend-sequelize-node
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
